#!/bin/sh
###############################
##----- Global settings -----##
###############################

#-help 

##################################
##----- Settings for T -----##
##################################
#--> KSP
-multiRegionMesh.T_ksp_type preonly

#--> PC
-multiRegionMesh.T_pc_type lu
-multiRegionMesh.T_pc_factor_mat_solver_type mumps






