#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_DIR/scripts/AllwmakeParseArguments

set -x

wmake rheoTestFoam

wmake rheoFoam

wmake libso rheoInterFoam/twoPhaseChange
wmake rheoInterFoam

wmake rheoEFoam

wmake rheoBDFoam

wmake rheoHeatFoam
wmake rheoMultiRegionFoam

wmake rheoFilmFoam
 
