#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_DIR/scripts/AllwmakeParseArguments

set -x

wmake libso fvmb
wmake libso sparseMatrixSolvers
wmake libso gaussDefCmpwConvectionScheme

wmake libso thermo

wmake libso constitutiveEquations
wmake libso EDFModels
wmake libso boundaryConditions
wmake libso filmCasting

wmake preProcessing/rndPerturbation
wmake preProcessing/initMolecules

wmake libso postProcessing/postProcUtils
wmake postProcessing/writeEfield
wmake postProcessing/averageMolcN
wmake postProcessing/averageMolcX

wmake libso brownianDynamics



