#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Manual clean to keep the mesh

cleanCase
rm -rf 0/alpha.water
rm -rf 0/alpha.water.gz

rm -rf 0/U
rm -rf 0/U.gz

rm -rf resume
rm -rf DropWidth.txt
