#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


if [ "$#" -ne 1 ]; then
    echo "ERROR: Illegal number of parameters"
    echo "Usage is: ./Allrun n" 
    echo "where n is the number of processors to be used"
    exit 1
fi
  
  
runApplication blockMesh
 
runApplication splitMeshRegions -overwrite
 
cp -rf constant/solid0.back/thermoProperties    constant/solid0/thermoProperties
cp -rf constant/solid1.back/thermoProperties    constant/solid1/thermoProperties

if [ "$1" -gt 1 ]; then
 foamDictionary -entry "numberOfSubdomains" -set $1 system/decomposeParDict
 foamDictionary -entry "simpleCoeffs.n" -set "( 1 $1 1 )" system/decomposeParDict
 runApplication decomposePar -allRegions -dict system/decomposeParDict  
 runParallel rheoMultiRegionFoam
 runApplication reconstructPar -latestTime -allRegions 
else
 runApplication rheoMultiRegionFoam
fi

runApplication paraFoam -touchAll

runApplication -s solid0 postProcess -func sampleDict -latestTime -region "solid0"
runApplication -s solid1 postProcess -func sampleDict -latestTime -region "solid1"
