#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

runApplication blockMesh

cp system/mirrorMeshDict0 system/mirrorMeshDict

runApplication mirrorMesh -noFunctionObjects -overwrite

rm -rf log.mirrorMesh

cp system/mirrorMeshDict1 system/mirrorMeshDict

runApplication mirrorMesh -noFunctionObjects -overwrite

rm -rf system/mirrorMeshDict 

runApplication topoSet

runApplication createPatch -overwrite



cp 0/C.org 0/C

runApplication setFields

runApplication $application
 
