#!/bin/sh
###############################
##----- Global settings -----##
###############################

#-help
#-info

##################################
##----- Settings for Uptau -----##
##################################
#--> KSP
-Uptau_ksp_type preonly

#--> PC
-Uptau_pc_type lu
-Uptau_pc_factor_mat_solver_type mumps
 

##################################
##----- Settings for ciPsi -----##
##################################
#--> KSP
-ciPsi_ksp_type preonly

#--> PC
-ciPsi_pc_type lu
-ciPsi_pc_factor_mat_solver_type mumps
 

