#!/bin/sh
###############################
##----- Global settings -----##
###############################

#-help

##################################
##----- Settings for Uptau -----##
##################################
#--> KSP
-Uptau_ksp_type preonly

#--> PC
-Uptau_pc_type lu
-Uptau_pc_factor_mat_solver_type mumps
