#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
 
cleanCase

(cd ./solid.mesh && ./Allclean)

rm -rf sphere rheoToolPP
 
rm -rf constant/polyMesh/cellToRegion

rm -rf constant/fluid
rm -rf constant/sphere
 

rm -rf 0/cellToRegion
rm -rf 0/fluid/cellToRegion
rm -rf 0/sphere/cellToRegion

rm -rf ./runCoupledT  Cd.txt Nu.txt TavSphere.txt
