#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Manual clean to keep the mesh
cleanTimeDirectories

find -name 'processor*' | xargs rm -rf
find -name 'postProcessing' | xargs rm -rf
find -name 'log.*' | xargs rm -rf
find -name 'dynamicCode' | xargs rm -rf 

