#!/bin/sh
###############################
##----- Global settings -----##
###############################

#-help

##################################
##----- Settings for Uptau -----##
##################################
#--> KSP
-Uptau_ksp_type preonly
-Uptau_ksp_max_it 2000
-Uptau_ksp_rtol 1e-15
-Uptau_ksp_atol 0
-Uptau_ksp_divtol 10

#--> PC
-Uptau_pc_type lu
-Uptau_pc_factor_mat_solver_type mumps
