#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Manual clean to keep the mesh

(cd relaxation && ./Allclean)

cleanCase

rm -rf constant/runTimeInfo
rm -rf 0/lagrangian
rm -rf rheoToolPP
rm -rf VTKMolecules
