#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
 
cleanCase

(cd ./calibrator && ./Allclean)

rm -rf rheoToolPP
 
rm -rf constant/polyMesh/cellToRegion

rm -rf constant/polymer
rm -rf constant/calibrator
 

rm -rf 0/cellToRegion
rm -rf 0/polymer/cellToRegion
rm -rf 0/calibrator/cellToRegion
 
