#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Manual clean to keep the mesh

cleanCase
cleanSamples
rm -rf Xl_down.txt
rm -rf Xl_top.txt
rm -rf Xr_down.txt
rm -rf Xr_top.txt
 
