#!/bin/sh
set -x

wmake libso constitutiveEquations
wmake libso gaussDefCmpwConvectionScheme
wmake libso EDFModels
wmake libso boundaryConditions

wmake libso postProcessing/postProcUtils
wmake preProcessing/rndPerturbation
wmake postProcessing/writeEfield



