#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
 
set -x

wclean rheoTestFoam

wclean rheoFoam
wclean rheoInterFoam
wclean rheoEFoam

wclean rheoBDFoam

wclean rheoHeatFoam
wclean rheoMultiRegionFoam
