#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Manual clean to keep the mesh
 
cleanCase
 
rm -rf constant/polyMesh/cellToRegion

rm -rf constant/solid0
rm -rf constant/solid1
 

rm -rf 0/cellToRegion
rm -rf 0/solid0/cellToRegion
rm -rf 0/solid1/cellToRegion
 
 
