#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -rf constant/polyMesh.org constant/polyMesh

# Get application directory
application=`getApplication`

runApplication decomposePar

runParallel $application

runApplication reconstructPar -latestTime
