#!/bin/sh
###############################
##----- Global settings -----##
###############################

#-help
#-info

##################################
##----- Settings for ciPsi -----##
##################################
#--> KSP
-ciPsi_ksp_type bcgs
-ciPsi_ksp_max_it 2000
-ciPsi_ksp_rtol 1e-15
-ciPsi_ksp_atol 0
-ciPsi_ksp_divtol 10

#--> PC
-ciPsi_pc_type lu
-ciPsi_pc_factor_mat_solver_type mumps
 
