#!/bin/sh
###############################
##----- Global settings -----##
###############################

#-help

##################################
##----- Settings for Uptau -----##
##################################
#--> KSP
-fluid.Uptau_ksp_type bcgs
-fluid.Uptau_ksp_max_it 2000
-fluid.Uptau_ksp_rtol 1e-15
-fluid.Uptau_ksp_atol 0
-fluid.Uptau_ksp_divtol 10

#--> PC
-fluid.Uptau_pc_type lu
-fluid.Uptau_pc_factor_mat_solver_type mumps
 
##################################
##----- Settings for T -----##
##################################
#--> KSP
-multiRegionMesh.T_ksp_type bcgs
-multiRegionMesh.T_ksp_max_it 2000
-multiRegionMesh.T_ksp_rtol 1e-15
-multiRegionMesh.T_ksp_atol 0
-multiRegionMesh.T_ksp_divtol 10

#--> PC
-multiRegionMesh.T_pc_type lu
-multiRegionMesh.T_pc_factor_mat_solver_type mumps






