#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

runApplication blockMesh
runApplication cellSet
runApplication refineMesh -dict -overwrite 

cp 0/C.org 0/C

runApplication setFields

runApplication $application
 
runApplication writeEfield
