#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

(cd solution1D && ./Allrun)

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`


mkdir 0

runApplication blockMesh

runApplication mapFields solution1D/ -consistent -sourceTime 'latestTime'

rm -rf 0/cCation_0
rm -rf 0/cCation_0.gz
rm -rf 0/cAnion_0
rm -rf 0/cAnion_0.gz

runApplication rndPerturbation

runApplication $application
 
