#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ "$#" -ne 1 ]; then
    echo "ERROR: Illegal number of parameters"
    echo "Usage is: ./Allrun n" 
    echo "where n is the number of processors to be used"
    exit 1
fi
   
runApplication blockMesh

runApplication extrudeMesh

if [ "$1" -gt 1 ]; then
 foamDictionary -entry "numberOfSubdomains" -set $1 system/decomposeParDict
 runApplication decomposePar 
 
 # Dummy to force compilation of dynamic code before parallel run.
 # This is to avoid error in parallel runs in OF 9.
 runApplication postProcess 
   
 runParallel rheoHeatFoam
 runApplication reconstructPar -latestTime   
else
 runApplication rheoHeatFoam
fi
 
